import Head from "next/head";
import Image from "next/image";
import ParallaxOne from "../components/ParallaxOne";
import ParallaxTwo from "../components/ParallaxTwo";
import Empower from "../content/Empower.mdx";
import OurServices from "../content/OurServices.mdx";
import OurTools from "../content/OurTools.mdx";
import GettingStarted from "../content/GettingStarted.mdx";
import Logo from "../public/logo.js";
import Footer from "../content/Footer.mdx"


export default function Home() {
  return (
    <div>
      <Head>
        <title>CyVerse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div style={{ marginTop: "3vh" }}>
          <h1 className="display-2 text-center mb-4">
            <a href="https://cyverse.org" alt="CyVerse">
              <Logo />
            </a>
          </h1>
          <Empower />
        </div>
      </div>
      <ParallaxOne />
      <div className="container">
        <div>
          <OurServices />
        </div>
      </div>
      <ParallaxTwo />
      <div className="container">
        <div>
          <OurTools />
          <GettingStarted />
        </div>
         <Footer />
      </div>
    </div>
  );
}
