import Head from 'next/head'
import Image from 'next/image'
import ParallaxOne from '../components/ParallaxOne'
import BlockOne from '../content/BlockOne.mdx'
import BlockTwo from "../content/BlockTwo.mdx";
import BlockThree from "../content/BlockThree.mdx";
import BlockFour from "../content/BlockFour.mdx";
import SideNav from "../components/sideNav.js"


export default function Home() {
  return (
    <div>
      <Head>
        <title>CyVerse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideNav />
      <div className="container">
        <h1 className="display-2 text-center">
          Welcome to <a href="https://cyverse.org">CyVerse!</a>
        </h1>
        <BlockOne />
      </div>

      <ParallaxOne />
      <div className="container">
        <BlockTwo />
        <ParallaxOne />
        <BlockThree />
        <BlockFour />
      </div>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by CyVerse
        </a>
      </footer>
    </div>
  );
}
