import Head from 'next/head'
import Image from 'next/image'
import ParallaxOne from '../components/ParallaxOne'
import ParallaxTwo from "../components/ParallaxTwo";
import BlockOne from '../content/BlockOne.mdx'
import BlockTwo from "../content/BlockTwo.mdx";
import BlockThree from "../content/BlockThree.mdx";
import BlockFour from "../content/BlockFour.mdx";
import Testimonials from "../content/Testimonials.mdx";
import SideNav from "../components/sideNav.js"
import Logo from "../public/logo.js"
import DEBlock from "../content/DEBlock.mdx";
import DataStoreDataCommons from "../content/DataStoreDataCommons.mdx";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CyVerse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-md" style={{marginTop:'3vh'}}>
        <h1 className="display-2 text-center mb-4">
          <a href="https://cyverse.org" alt="CyVerse">
            <Logo />
          </a>
        </h1>
        <BlockOne />
      </div>
      <ParallaxOne />
      <div className="container">
        <BlockTwo />
      </div>
      <ParallaxTwo />
      <div className="container">
        <BlockThree />
        <DEBlock />
        <DataStoreDataCommons />
        <BlockFour />
      </div>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by CyVerse
        </a>
      </footer>
    </div>
  );
}
